# Generated by Django 2.0.13 on 2019-04-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(blank=True, db_column='ID', max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('role', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('contact_no', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=50)),
                ('nid', models.IntegerField(blank=True, db_column='NID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=30)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('lat', models.FloatField(blank=True, default=23.758642)),
                ('lon', models.FloatField(blank=True, default=90.390171)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MessagesUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(blank=True, max_length=50, null=True)),
                ('reciever', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'home_messagesuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('service_type', models.IntegerField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('radius', models.IntegerField()),
            ],
            options={
                'db_table': 'req',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('email', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('contact_no', models.CharField(blank=True, max_length=11)),
                ('nid', models.IntegerField(blank=True, db_column='NID')),
                ('service_type', models.CharField(blank=True, max_length=1)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('verified', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=30)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('lat', models.FloatField(blank=True, default=23.758642)),
                ('lon', models.FloatField(blank=True, default=90.390171)),
                ('radius', models.IntegerField()),
            ],
            options={
                'db_table': 'service_provider',
                'managed': False,
            },
        ),
    ]
